windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = center,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 62% 72%,class:^(org.pulseaudio.pavucontrol)$

windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = center,class:^(nm-connection-editor)$
windowrulev2 = size 60% 70%,class:^(nm-connection-editor)$

# nm-applet 弹出窗口（密码对话框等）：浮动 + 置顶 + 可点击外部关闭
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = pin,class:^(nm-applet)$
windowrulev2 = stayfocused,class:^(nm-applet)$
windowrulev2 = dimaround,class:^(nm-applet)$

# Polkit 认证弹窗
windowrulev2 = float,class:^(hyprpolkitagent)$
windowrulev2 = pin,class:^(hyprpolkitagent)$
windowrulev2 = stayfocused,class:^(hyprpolkitagent)$
windowrulev2 = dimaround,class:^(hyprpolkitagent)$
